#!/bin/sh
#
# AppRun script for AppImage using proot and {{{ 100% POSIX }}}
#
# By Mauricio Ferrari (m10ferrari1200@gmail.com)
#
###############################################################################

APPDIR="$(cd -- "${0%/*}" && pwd -P)"

PROGRAM=
PARM=
ENABLE_NVIDIA=${ENABLE_NVIDIA:-0}
AUTO_INTEGRATION=${AUTO_INTEGRATION:-0}
AUTOSTART=${AUTOSTART:-0}
AUTOSTART_PARM=
DESKTOP=
ICON=

test $ENABLE_NVIDIA -eq 1 && source "$APPDIR/DetectNVidia"

if test $AUTO_INTEGRATION -eq 1 && command -v grep >/dev/null && command -v sed >/dev/null
then
    local_desktop=~/.local/share/applications
    local_icon=~/.local/share/pixmaps
    local_autostart=~/.config/autostart

    mkdir -p "$local_desktop" "$local_icon" "$local_autostart"

    cp -nv "$APPDIR/$DESKTOP" "$local_desktop"
    cp -nv "$APPDIR/$ICON" "$local_icon"

    if ! grep -q "$APPIMAGE" "$local_desktop/$DESKTOP"
    then
        sed -i -e "s|Exec=[^ ]*|Exec=${APPIMAGE}|" -e "s|Icon=.*|Icon=${ICON%.*}|" "$local_desktop/$DESKTOP"

        if test $AUTOSTART -eq 1
        then
            cp -nv "$APPDIR/$DESKTOP" "$local_autostart"

            autoparm=${AUTOSTART_PARM:+" $AUTOSTART_PARM"}
            sed -i -e "s|Exec=[^ ]*|Exec=${APPIMAGE}${autoparm}|" -e "s|Icon=.*|Icon=${ICON%.*}|" "$local_desktop/$DESKTOP"
        fi

        command -v update-desktop-database >/dev/null && update-desktop-database -q >/dev/null 2>&1

        if test -e "usr/share/icons/hicolor/icon-theme.cache" && command -v gtk-update-icon-cache >/dev/null
        then
            gtk-update-icon-cache ~/.local/share/pixmaps/ >/dev/null 2>&1
        fi
    fi
fi

export LIBRARY_PATH="$APPDIR/lib:$APPDIR/lib64:$APPDIR/usr/lib:$APPDIR/usr/lib64:$APPDIR/lib/x86_64-linux-gnu:$APPDIR/usr/lib/x86_64-linux-gnu"

PROOT_OPTIONS="-R $APPDIR \
    --bind=/dev \
    --bind=/sys \
    --bind=/tmp \
    --bind=/proc \
    --bind=/etc/resolv.conf \
    --bind=/etc/hosts \
    --bind=/etc/nsswitch.conf \
    --bind=/etc/passwd \
    --bind=/etc/group \
    --bind=/etc/machine-id \
    --bind=/etc/asound.conf \
    --bind=/etc/localtime \
    --bind=/home \
    --bind=/media \
    --bind=/mnt \
    --bind=/opt \
    --bind=/run \
    --bind=/etc/fonts \
    --bind=/usr/lib/locale \
    --bind=/usr/share/font-config \
    --bind=/usr/share/fonts \
    --bind=/usr/share/themes \
    --bind=/var ${PROOT_NVIDIA_HARDWARE_ACCELERATION:+$PROOT_NVIDIA_HARDWARE_ACCELERATION}
"

export LD_LIBRARY_PATH="/usr/lib:/lib:/usr/lib64:/lib64:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu${NV_LIBRARY:+:$NV_LIBRARY}"
exec "$APPDIR/usr/lib/ld-linux-x86-64.so.2" --inhibit-cache --library-path "${LIBRARY_PATH}" "$APPDIR/usr/bin/proot-x86_64" $PROOT_OPTIONS "$PROGRAM" $PARM "$@"  # parms no "parms"
