#!/bin/sh
#
# AppRun script for AppImage using bwrap and POSIX-compliant sh standard
#
# By Mauricio Ferrari (m10ferrari1200@gmail.com)
#
###########################################################################

APPDIR="$(cd -- "${0%/*}" && pwd -P)"

#_______________________________________________

# PROGRAM
# - /usr/bin/program

# LD_LINUX
# - $APPDIR/usr/lib/ld-linux-x86-64.so.2

PROGRAM=
LD_LINUX=

AUTO_INTEGRATION=0
AUTOSTART=0
AUTOSTART_PARM=
DESKTOP=
ICON=

#_______________________________________________


if test ${AUTO_INTEGRATION:-0} -eq 1 && command -v grep >/dev/null && command -v sed >/dev/null
then
    local_desktop=~/.local/share/applications
    local_icon=~/.local/share/pixmaps
    local_autostart=~/.config/autostart

    mkdir -p "$local_desktop" "$local_icon" "$local_autostart"

    cp -nv "$APPDIR/$DESKTOP" "$local_desktop"
    cp -nv "$APPDIR/$ICON" "$local_icon"

    if ! grep -q "$APPIMAGE" "$local_desktop/$DESKTOP"
    then
        sed -i "s|Exec=[^ ]*|Exec=${APPIMAGE}|" "$local_desktop/$DESKTOP"
        sed -i "s|Icon=.*|Icon=${ICON%.*}|" "$local_desktop/$DESKTOP"

        if test ${AUTOSTART:-0} -eq 1
        then
            cp -nv "$APPDIR/$DESKTOP" "$local_autostart"

            autoparm=${AUTOSTART_PARM:+" $AUTOSTART_PARM"}
            sed -i "s|Exec=[^ ]*|Exec=${APPIMAGE}${autoparm}|" "$local_autostart/$DESKTOP"
            sed -i "s|Icon=.*|Icon=${ICON%.*}|" "$local_desktop/$DESKTOP"
        fi

        if command -v update-desktop-database >/dev/null
        then
            update-desktop-database -q >/dev/null 2>&1
        fi

        if test -e "usr/share/icons/hicolor/icon-theme.cache" && command -v gtk-update-icon-cache >/dev/null
        then
            gtk-update-icon-cache ~/.local/share/pixmaps/ >/dev/null 2>&1
        fi
    fi
fi

export LIBRARY_PATH="$APPDIR/lib:$APPDIR/lib64:$APPDIR/usr/lib:$APPDIR/usr/lib64"

BWRAP_OPTIONS="--unshare-user --bind $APPDIR / \
    --share-net \
    --dev-bind /dev /dev \
    --ro-bind /sys /sys \
    --proc /proc \
    --ro-bind-try /etc/resolv.conf /etc/resolv.conf \
    --ro-bind-try /etc/hosts /etc/hosts \
    --ro-bind-try /etc/nsswitch.conf /etc/nsswitch.conf \
    --ro-bind-try /etc/passwd /etc/passwd \
    --ro-bind-try /etc/group /etc/group \
    --ro-bind-try /etc/machine-id /etc/machine-id \
    --ro-bind-try /etc/asound.conf /etc/asound.conf \
    --ro-bind-try /etc/localtime /etc/localtime \
    --bind-try /lib/firmware /lib/firmware \
    --bind-try /home /home \
    --bind-try /media /media \
    --bind-try /mnt /mnt \
    --bind-try /opt /opt \
    --bind-try /tmp /tmp \
    --bind-try /run /run \
    --bind-try /etc/fonts /etc/fonts \
    --bind-try /usr/lib/locale /usr/lib/locale \
    --bind-try /usr/share/font-config /usr/share/font-config \
    --bind-try /usr/share/fonts /usr/share/fonts \
    --bind-try /usr/share/themes /usr/share/themes \
    --bind-try /var /var \
    --setenv BWROOTFS \"$APPDIR\"
"

if command -v xhost
then
    xhost -SI:localuser:$USER
fi

exec "${LD_LINUX:-$APPDIR/lib64/ld-linux-x86-64.so.2}" --inhibit-cache --library-path "${LIBRARY_PATH}" "$APPDIR/usr/bin/bwrap" $BWRAP_OPTIONS "$PROGRAM" "$@"
