#!/bin/sh
#
# AppRun script for AppImage using junest with fallback proot and {{{ 100% POSIX }}}
#
# By Mauricio Ferrari (m10ferrari1200@gmail.com)
#
#########################################################################################

APPDIR="$(cd -- "${0%/*}" && pwd -P)"

PROGRAM=
PARM=
ENABLE_NVIDIA=${ENABLE_NVIDIA:-0}
AUTO_INTEGRATION=${AUTO_INTEGRATION:-0}
AUTOSTART=${AUTOSTART:-0}
AUTOSTART_PARM=
DESKTOP=
ICON=

test $ENABLE_NVIDIA -eq 1 && source "$APPDIR/DetectNVidia"

if test $AUTO_INTEGRATION -eq 1 && command -v grep >/dev/null && command -v sed >/dev/null
then
    local_desktop=~/.local/share/applications
    local_icon=~/.local/share/pixmaps
    local_autostart=~/.config/autostart

    mkdir -p "$local_desktop" "$local_icon" "$local_autostart"

    cp -nv "$APPDIR/$DESKTOP" "$local_desktop"
    cp -nv "$APPDIR/$ICON" "$local_icon"

    if ! grep -q "$APPIMAGE" "$local_desktop/$DESKTOP"
    then
        sed -i -e "s|Exec=[^ ]*|Exec=${APPIMAGE}|" -e "s|Icon=.*|Icon=${ICON%.*}|" "$local_desktop/$DESKTOP"

        if test $AUTOSTART -eq 1
        then
            cp -nv "$APPDIR/$DESKTOP" "$local_autostart"

            autoparm=${AUTOSTART_PARM:+" $AUTOSTART_PARM"}
            sed -i -e "s|Exec=[^ ]*|Exec=${APPIMAGE}${autoparm}|" -e "s|Icon=.*|Icon=${ICON%.*}|" "$local_desktop/$DESKTOP"
        fi

        command -v update-desktop-database >/dev/null && update-desktop-database -q >/dev/null 2>&1

        if test -e "usr/share/icons/hicolor/icon-theme.cache" && command -v gtk-update-icon-cache >/dev/null
        then
            gtk-update-icon-cache ~/.local/share/pixmaps/ >/dev/null 2>&1
        fi
    fi
fi

export UNION_PRELOAD="$APPDIR"
export JUNEST_HOME="$APPDIR"

BWRAP_BINDS=" --dev-bind /dev /dev \
    --ro-bind /sys /sys \
    --bind-try /tmp /tmp \
    --proc /proc \
    --ro-bind-try /etc/resolv.conf /etc/resolv.conf \
    --ro-bind-try /etc/hosts /etc/hosts \
    --ro-bind-try /etc/nsswitch.conf /etc/nsswitch.conf \
    --ro-bind-try /etc/passwd /etc/passwd \
    --ro-bind-try /etc/group /etc/group \
    --ro-bind-try /etc/machine-id /etc/machine-id \
    --ro-bind-try /etc/asound.conf /etc/asound.conf \
    --ro-bind-try /etc/localtime /etc/localtime \
    --bind-try /home /home \
    --bind-try /media /media \
    --bind-try /mnt /mnt \
    --bind-try /opt /opt \
    --bind-try /run /run \
    --bind-try /etc/fonts /etc/fonts \
    --bind-try /usr/lib/locale /usr/lib/locale \
    --bind-try /usr/share/font-config /usr/share/font-config \
    --bind-try /usr/share/fonts /usr/share/fonts \
    --bind-try /usr/share/themes /usr/share/themes \
    --bind-try /var /var ${BWRAP_NVIDIA_HARDWARE_ACCELERATION:+$BWRAP_NVIDIA_HARDWARE_ACCELERATION}
"

PROOT_BINDS="--bind=/dev \
    --bind=/sys \
    --bind=/tmp \
    --bind=/proc \
    --bind=/etc/resolv.conf \
    --bind=/etc/hosts \
    --bind=/etc/nsswitch.conf \
    --bind=/etc/passwd \
    --bind=/etc/group \
    --bind=/etc/machine-id \
    --bind=/etc/asound.conf \
    --bind=/etc/localtime \
    --bind=/home \
    --bind=/media \
    --bind=/mnt \
    --bind=/opt \
    --bind=/run \
    --bind=/etc/fonts \
    --bind=/usr/lib/locale \
    --bind=/usr/share/font-config \
    --bind=/usr/share/fonts \
    --bind=/usr/share/themes \
    --bind=/var ${PROOT_NVIDIA_HARDWARE_ACCELERATION:+$PROOT_NVIDIA_HARDWARE_ACCELERATION}
"

if command -v unshare >/dev/null 2>&1 && ! unshare --user -p /bin/true >/dev/null 2>&1
then
    printf "using proot ...\n"
    export LD_LIBRARY_PATH="/usr/lib:/lib:/usr/lib64:/lib64${NV_LIBRARY:+:$NV_LIBRARY}"
    "$APPDIR/junest/bin/junest" proot -n -b "$PROOT_BINDS" -- "$PROGRAM" $PARM "$@"  # parms no "parms"
else
    printf "using bwrap ...\n"
    command -v xhost && xhost -SI:localuser:"$USER"  # debian
    export LD_LIBRARY_PATH="/usr/lib:/lib:/usr/lib64:/lib64${NV_LIBRARY:+:$NV_LIBRARY}"
    "$APPDIR/junest/bin/junest" -n -b "$BWRAP_BINDS" -- "$PROGRAM" $PARM "$@"  # parms no "parms"
fi
