#!/bin/sh
#
# Conteiner AppRun for AppImage
#
# By Mauricio Ferrari (m10ferrari1200@gmail.com)
#
################################################

APPDIR="$(dirname "$(readlink -f $0)")"

#_______________________________________________

# PROGRAM
# - /usr/bin/program

PROGRAM=

#_______________________________________________

export UNION_PRELOAD="$APPDIR"
export JUNEST_HOME="$APPDIR"

BINDS=" --dev-bind /dev /dev \
    --ro-bind /sys /sys \
    --bind-try /tmp /tmp \
    --proc /proc \
    --ro-bind-try /etc/resolv.conf /etc/resolv.conf \
    --ro-bind-try /etc/hosts /etc/hosts \
    --ro-bind-try /etc/nsswitch.conf /etc/nsswitch.conf \
    --ro-bind-try /etc/passwd /etc/passwd \
    --ro-bind-try /etc/group /etc/group \
    --ro-bind-try /etc/machine-id /etc/machine-id \
    --ro-bind-try /etc/asound.conf /etc/asound.conf \
    --ro-bind-try /etc/localtime /etc/localtime \
    --bind-try /media /media \
    --bind-try /mnt /mnt \
    --bind-try /opt /opt \
    --bind-try /run/media /run/media \
    --bind-try /etc/fonts /etc/fonts \
    --bind-try /usr/lib/locale /usr/lib/locale \
    --bind-try /usr/share/font-config /usr/share/font-config \
    --bind-try /usr/share/fonts /usr/share/fonts \
    --bind-try /usr/share/themes /usr/share/themes \
    --bind-try /var /var"

"$APPDIR/junest/bin/junest" -n -b "$BINDS" -- "$PROGRAM" "$@"
