#!/bin/bash
#
# Default AppRun for Tarball AppImage and {{{ 100% POSIX }}}
#
# By Mauricio Ferrari (m10ferrari1200@gmail.com)
#
###############################################################################

APPDIR="$(cd -- "${0%/*}" && pwd -P)"

PROGRAM=
PARM=
ENABLE_SUDO=0
AUTO_INTEGRATION=${AUTO_INTEGRATION:-0}
AUTOSTART=${AUTOSTART:-0}
AUTOSTART_PARM=
DESKTOP=
ICON=


if test "$UID" -ne 0 && command -v pkexec && test ${ENABLE_SUDO:-0} -eq 1
then
    pkexec env DISPLAY="$DISPLAY" XAUTHORITY="$XAUTHORITY" "$APPIMAGE" "$@"
    exit 0
fi

if test $AUTO_INTEGRATION -eq 1 && command -v grep >/dev/null && command -v sed >/dev/null
then
    local_desktop=~/.local/share/applications
    local_icon=~/.local/share/pixmaps
    local_autostart=~/.config/autostart

    mkdir -p "$local_desktop" "$local_icon" "$local_autostart"

    cp -nv "$APPDIR/$DESKTOP" "$local_desktop"
    cp -nv "$APPDIR/$ICON" "$local_icon"

    if ! grep -q "$APPIMAGE" "$local_desktop/$DESKTOP"
    then
        sed -i -e "s|Exec=[^ ]*|Exec=${APPIMAGE}|" -e "s|Icon=.*|Icon=${ICON%.*}|" "$local_desktop/$DESKTOP"

        if test $AUTOSTART -eq 1
        then
            cp -nv "$APPDIR/$DESKTOP" "$local_autostart"

            autoparm=${AUTOSTART_PARM:+" $AUTOSTART_PARM"}
            sed -i -e "s|Exec=[^ ]*|Exec=${APPIMAGE}${autoparm}|" -e "s|Icon=.*|Icon=${ICON%.*}|" "$local_desktop/$DESKTOP"
        fi

        command -v update-desktop-database >/dev/null && update-desktop-database -q >/dev/null 2>&1

        if test -e "usr/share/icons/hicolor/icon-theme.cache" && command -v gtk-update-icon-cache >/dev/null
        then
            gtk-update-icon-cache ~/.local/share/pixmaps/ >/dev/null 2>&1
        fi
    fi
fi

exec "$PROGRAM" $PARM "$@"
