#!/bin/sh
#
# Conteiner AppRun for AppImage
#
# By Mauricio Ferrari (m10ferrari1200@gmail.com)
#
################################################

APPDIR="$(dirname "$(readlink -f $0)")"

#_______________________________________________

# PROGRAM
# - /usr/bin/program

PROGRAM=

AUTO_INTEGRATION=0
AUTOSTART=0
AUTOSTART_PARM=
DESKTOP=
ICON=

#_______________________________________________


test $AUTO_INTEGRATION -eq 0 || {
    local_desktop=~/.local/share/applications
    local_icon=~/.local/share/pixmaps
    local_autostart=~/.config/autostart

    test -d "$local_desktop" || mkdir -p "$local_desktop"
    test -d "$local_icon" || mkdir -p "$local_icon"

    test -f "$local_desktop/$DESKTOP" || cp "$APPDIR/$DESKTOP" "$local_desktop"
    test -f "$local_icon/$ICON" || cp "$APPDIR/$ICON" "$local_icon"

    test $AUTOSTART -eq 0 || {
        test -d "$local_autostart" || mkdir -p "$local_autostart"
        test -f "$local_autostart/$DESKTOP" || cp "$APPDIR/$DESKTOP" "$local_autostart"
    }

    grep -q "$APPIMAGE" "$local_desktop/$DESKTOP" || {

        parm="$( grep -o " .*"  <( grep -m1 "^Exec=.*" "$APPDIR/$DESKTOP" ))"

        sed -i "s|Exec=.*|Exec=${APPIMAGE}${parm}|" "$local_desktop/$DESKTOP"
        sed -i "s|Icon=.*|Icon=${ICON%[.]*}|" "$local_desktop/$DESKTOP"

        test $AUTOSTART -eq 0 || {
            autoparm=${AUTOSTART_PARM:+" $AUTOSTART_PARM"}
            sed -i "s|Exec=.*|Exec=${APPIMAGE}${autoparm}${parm}|" "$local_autostart/$DESKTOP"
            sed -i "s|Icon=.*|Icon=${ICON%[.]*}|" "$local_autostart/$DESKTOP"
        }

        /usr/bin/update-desktop-database -q 2>&1 >&-

        test -e usr/share/icons/hicolor/icon-theme.cache && \
            test -x /usr/bin/gtk-update-icon-cache && \
                /usr/bin/gtk-update-icon-cache ~/.local/share/pixmaps/ 2>&1 >&-
    }
}

export UNION_PRELOAD="$APPDIR"
export JUNEST_HOME="$APPDIR"

BINDS=" --dev-bind /dev /dev \
    --ro-bind /sys /sys \
    --bind-try /tmp /tmp \
    --proc /proc \
    --ro-bind-try /etc/resolv.conf /etc/resolv.conf \
    --ro-bind-try /etc/hosts /etc/hosts \
    --ro-bind-try /etc/nsswitch.conf /etc/nsswitch.conf \
    --ro-bind-try /etc/passwd /etc/passwd \
    --ro-bind-try /etc/group /etc/group \
    --ro-bind-try /etc/machine-id /etc/machine-id \
    --ro-bind-try /etc/asound.conf /etc/asound.conf \
    --ro-bind-try /etc/localtime /etc/localtime \
    --bind-try /media /media \
    --bind-try /mnt /mnt \
    --bind-try /opt /opt \
    --bind-try /run/media /run/media \
    --bind-try /etc/fonts /etc/fonts \
    --bind-try /usr/lib/locale /usr/lib/locale \
    --bind-try /usr/share/font-config /usr/share/font-config \
    --bind-try /usr/share/fonts /usr/share/fonts \
    --bind-try /usr/share/themes /usr/share/themes \
    --bind-try /var /var"

"$APPDIR/junest/bin/junest" -n -b "$BINDS" -- "$PROGRAM" "$@"
