#!/bin/bash
#
# Universal AppRun for AppImage
#
# By Mauricio Ferrari (m10ferrari1200@gmail.com)
#
################################################

APPDIR="$(cd "${0%/*}" && echo $PWD)"

#_______________________________________________

# PROGRAM
# - /usr/bin/program

# LD_LINUX
# - $APPDIR/usr/lib/ld-linux-x86-64.so.2

PROGRAM=
LD_LINUX=

AUTO_INTEGRATION=0
AUTOSTART=0
AUTOSTART_PARM=
DESKTOP=
ICON=

#_______________________________________________


test $AUTO_INTEGRATION -eq 0 || {
    local_desktop=~/.local/share/applications
    local_icon=~/.local/share/pixmaps
    local_autostart=~/.config/autostart

    test -d "$local_desktop" || mkdir -p "$local_desktop"
    test -d "$local_icon" || mkdir -p "$local_icon"

    test -f "$local_desktop/$DESKTOP" || cp "$APPDIR/$DESKTOP" "$local_desktop"
    test -f "$local_icon/$ICON" || cp "$APPDIR/$ICON" "$local_icon"

    test $AUTOSTART -eq 0 || {
        test -d "$local_autostart" || mkdir -p "$local_autostart"
        test -f "$local_autostart/$DESKTOP" || cp "$APPDIR/$DESKTOP" "$local_autostart"
    }

    test -z "$DESKTOP" || {
        grep -q "$APPIMAGE" "$local_desktop/$DESKTOP" || {

            parm="$( grep -o " .*"  <( grep -m1 "^Exec=.*" "$APPDIR/$DESKTOP" ))"

            sed -i "s|Exec=.*|Exec=${APPIMAGE}${parm}|" "$local_desktop/$DESKTOP"
            sed -i "s|Icon=.*|Icon=${ICON%[.]*}|" "$local_desktop/$DESKTOP"

            test $AUTOSTART -eq 0 || {
                autoparm=${AUTOSTART_PARM:+" $AUTOSTART_PARM"}
                sed -i "s|Exec=.*|Exec=${APPIMAGE}${autoparm}${parm}|" "$local_autostart/$DESKTOP"
                sed -i "s|Icon=.*|Icon=${ICON%[.]*}|" "$local_autostart/$DESKTOP"
            }

            /usr/bin/update-desktop-database -q 2>&1 >&-

            test -e usr/share/icons/hicolor/icon-theme.cache && \
                test -x /usr/bin/gtk-update-icon-cache && \
                    /usr/bin/gtk-update-icon-cache ~/.local/share/pixmaps/ 2>&1 >&-
        }
    }
}

IFS_BAK=$IFS
IFS=:

export LIBRARY_PATH="$(i=($APPDIR*/{,usr/}lib{/,/{i386,x86_64}-linux-gnu/,64/}{,*/}); echo "${i[*]}")"

IFS=$IFS_BAK

PROOT_OPTIONS="-R $APPDIR \
    --bind=/dev \
    --bind=/sys \
    --bind=/tmp \
    --bind=/proc \
    --bind=/etc/resolv.conf \
    --bind=/etc/hosts \
    --bind=/etc/nsswitch.conf \
    --bind=/etc/passwd \
    --bind=/etc/group \
    --bind=/etc/machine-id \
    --bind=/etc/asound.conf \
    --bind=/etc/localtime \
    --bind=/lib/firmware \
    --bind=/home --bind=/home/$USER \
    --bind=/media \
    --bind=/mnt \
    --bind=/opt \
    --bind=/run \
    --bind=/etc/fonts \
    --bind=/usr/lib/locale \
    --bind=/usr/share/font-config \
    --bind=/usr/share/fonts \
    --bind=/usr/share/themes \
    --bind=/var
"

test -z "$PROGRAM" || exec "${LD_LINUX:-$APPDIR/lib64/ld-linux-x86-64.so.2}" \
    --inhibit-cache \
    --library-path "${LIBRARY_PATH}" \
    "$APPDIR/usr/bin/proot-x86_64" $PROOT_OPTIONS "$PROGRAM" "$@"
